---
title: "Academic promotion information"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Research

## Teaching

## Engagement

Contributors: Belinda Fabian & Ly Tong

This section includes suggestions for engagement activities that could be included in academic promotion applications. These examples are indicative only and do not provide a list of expectations. Engagement is interpreted in a broad sense to include discipline, industry, government and community engagement. 

Engagement with industry
- Partnerships with organisations: for profit, not-for-profit, volunteering
- Consulting projects -> could list value of projects, reports completed
- Participation in project development programs e.g. CSIRO On Prime
- Patents
- Service on industry boards and/or committees at the local, state or national level

Engagement with government
- Policy development -> changes resulting from your work
- Advocacy programs e.g. Science Meets Parliament 
- Service with government bodies 

Engagement with public 
- Public presentations - list of locations
- Blogging (own blog or collaborative) --> stats available from blog backend e.g. views, visitors, followers
- Twitter --> number of followers from profile, Twitter analytics https://analytics.twitter.com shows impressions, engagament rate, likes, retweets, replies (only allows viewing of the last 90 days of data)
- Community programs e.g. National Science Week, 
- Media appearances e.g. appearances on TV, radio, web
- Writing for general audience e.g. The Conversation, university news platforms (e.g. The Lighthouse)
- Public works e.g. art installations, consulting on museum exhibit
- Service on community boards and/or committees at the local, state or national level

Engagement with professional community
- Contributions to community support websites e.g. Stack Overflow
- Data science competitions e.g. Kaggle
- Community engagement projects e.g. citizen science
- Community development e.g. meetup groups, RLadies, rOpenSci, hackathons
- Creation of software packages/tools for open use

Engagement with schools
- curriculum development e.g. STEM at School 
- interactions with school students e.g. Skype a Scientist (discussing science with students)
- supervising students e.g. work experience placements, mentoring projects
- University events e.g. Open Day

Contributions to enhancing the employability of graduates
- establishing student links with industry/professional societies
- participating in professional practice teaching e.g. teamwork, communication, problem solving, grant writing

Engagement/leadership within one’s profession or discipline
- Professional society membership & activity
- Membership of professional or foundation boards/councils
- Peer review (IF NOT INCLUDED IN RESEARCH SECTION) -> journal article review, ARC college of experts, grant review panels

## Leadership
